In [2]:
%matplotlib inline


# Tensors
--------------------------------------------

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you’re familiar with ndarrays, you’ll
be right at home with the Tensor API. If not, follow along in this quick
API walkthrough.




In [3]:
import torch
import numpy as np

## Tensor Initialization

Tensors can be initialized in various ways. Take a look at the following examples:

### Directly from data

Tensors can be created directly from data. The data type is automatically inferred.



In [8]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### From a NumPy array

Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`).



In [11]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
np_array

array([[1, 2],
       [3, 4]])

### From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [12]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0807, 0.9938],
        [0.8256, 0.9602]]) 



### With random or constant values:

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [13]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6448, 0.2579, 0.4555],
        [0.6476, 0.7840, 0.2139]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




## Tensor Attributes

Tensor attributes describe their shape, datatype, and the device on which they are stored.



In [20]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




## Tensor Operations

Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described [here](https://pytorch.org/docs/stable/torch.html)

Each of them can be run on the GPU (at typically higher speeds than on a
CPU). If you’re using Colab, allocate a GPU by going to Edit > Notebook
Settings.




In [18]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.




### Standard numpy-like indexing and slicing:



In [19]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining tensors
You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining op that is subtly different from ``torch.cat``.



In [21]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.1473, 0.3972, 0.3576, 0.9853, 0.1473, 0.3972, 0.3576, 0.9853, 0.1473,
         0.3972, 0.3576, 0.9853],
        [0.4940, 0.3320, 0.1900, 0.6833, 0.4940, 0.3320, 0.1900, 0.6833, 0.4940,
         0.3320, 0.1900, 0.6833],
        [0.2642, 0.9388, 0.1511, 0.9483, 0.2642, 0.9388, 0.1511, 0.9483, 0.2642,
         0.9388, 0.1511, 0.9483]])


### Multiplying tensors



In [22]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[0.0217, 0.1578, 0.1278, 0.9707],
        [0.2441, 0.1102, 0.0361, 0.4670],
        [0.0698, 0.8813, 0.0228, 0.8993]]) 

tensor * tensor 
 tensor([[0.0217, 0.1578, 0.1278, 0.9707],
        [0.2441, 0.1102, 0.0361, 0.4670],
        [0.0698, 0.8813, 0.0228, 0.8993]])


This computes the matrix multiplication between two tensors



In [23]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[1.2781, 0.9459, 1.4002],
        [0.9459, 0.8574, 1.1189],
        [1.4002, 1.1189, 1.8732]]) 

tensor @ tensor.T 
 tensor([[1.2781, 0.9459, 1.4002],
        [0.9459, 0.8574, 1.1189],
        [1.4002, 1.1189, 1.8732]])


### In-place operations
Operations that have a ``_`` suffix are in-place. For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



In [24]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.1473, 0.3972, 0.3576, 0.9853],
        [0.4940, 0.3320, 0.1900, 0.6833],
        [0.2642, 0.9388, 0.1511, 0.9483]]) 

tensor([[5.1473, 5.3972, 5.3576, 5.9853],
        [5.4940, 5.3320, 5.1900, 5.6833],
        [5.2642, 5.9388, 5.1511, 5.9483]])


<div class="alert alert-info">Note<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss
     of history. Hence, their use is discouraged.</p></div>



--------------




## Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change	the other.



### Tensor to NumPy array

In [25]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.



In [26]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [27]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.



In [28]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
