# Tensors 1D

## The basics

### tensors, dtype, type()

In [2]:
import torch
a=torch.tensor([7,4,3,2,6])

In [3]:
a

tensor([7, 4, 3, 2, 6])

In [4]:
a[4]

tensor(6)

In [5]:
a.dtype

torch.int64

In [6]:
a.type()

'torch.LongTensor'

### tensors of float

In [7]:
a=torch.tensor([0.0, 1.0, 2.1, 3.0, 4.0])

In [8]:
a

tensor([0.0000, 1.0000, 2.1000, 3.0000, 4.0000])

In [9]:
a.dtype

torch.float32

In [10]:
a.type()

'torch.FloatTensor'

### force tensor type

In [11]:
a=torch.tensor([0.0,1.0,2.0,3.0,4.0], dtype=torch.int32)

<ipython-input-11-d6616eab2e34>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  a=torch.tensor([0.0,1.0,2.0,3.0,4.0], dtype=torch.int32)


In [12]:
a.dtype

torch.int32

### FloatTensor

In [13]:
import torch
a=torch.FloatTensor([0,1,2,3,4])

In [14]:
a

tensor([0., 1., 2., 3., 4.])

### Convert with .type()

In [15]:
import torch
a=torch.tensor([0,1,2,3,4])
a=a.type(torch.FloatTensor)

In [17]:
a.type()

'torch.FloatTensor'

### size(), ndimension()

In [19]:
a=torch.Tensor([0,1,2,3,4])

In [20]:
a.size()

torch.Size([5])

In [21]:
a.ndimension()

1

### tensor vs Tensor

https://stackoverflow.com/questions/51911749/what-is-the-difference-between-torch-tensor-and-torch-tensor

torch.tensor infers the dtype automatically, while torch.Tensor returns a torch.FloatTensor. I would recommend to stick to torch.tensor, which also has arguments like dtype, if you would like to change the type.

### convert 1D to 2D using view

In [22]:
a=torch.Tensor([0,1,2,3,4])
a_col = a.view(5,1)

In [23]:
a_col

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [24]:
b_col = a.view(-1,1)
b_col

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [25]:
a_col.ndimension()

2

### create torch tensors from numpy arrays: from_numpy, numpy()

In [26]:
import numpy as np
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0])

In [27]:
torch_tensor = torch.from_numpy(numpy_array)
back_to_numpy = torch_tensor.numpy()

In [28]:
torch_tensor

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

In [29]:
back_to_numpy

array([0., 1., 2., 3., 4.])

### pandas series to torch tensors

In [32]:
import pandas as pd
pandas_series = pd.Series([0.1, 2, 0.3, 10.1])
pandas_series

0     0.1
1     2.0
2     0.3
3    10.1
dtype: float64

In [33]:
pandas_to_torch = torch.from_numpy(pandas_series.values)

In [34]:
pandas_to_torch

tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)

### tensor to list: tolist()

In [35]:
this_tensor = torch.tensor([0, 1, 2, 3])
torch_to_list = this_tensor.tolist()
torch_to_list

[0, 1, 2, 3]

### item to return a number

In [36]:
new_tensor = torch.tensor([5, 2, 6, 1])
new_tensor[0]

tensor(5)

In [37]:
new_tensor[0].item()

5

## indexing and slicing